name: deploy
 
on: workflow_dispatch
     
 
env:
  CLUSTER_NAME: myakscluster
  RESOURCE_GROUP: aksRG
 
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2

      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.18.8'

      - uses: azure/setup-helm@v1
        with:
          version: latest
          id: install
 
      - uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}

      - run: |
          helm install myapp-github-demo ./aks-helm/myapp2

      